<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Optimized Path Image</title>
</head>
<body>
    <h1>Optimized Path Image</h1>
    <p>This page displays the optimized path image:</p>

    <?php
    // Read the content of the HTML file generated by the Python script
    $htmlFilePath = 'C:\xampp\htdocs\gms\newcheck.html'; // Replace with the actual path
    $htmlContent = file_get_contents($htmlFilePath);

    // Display the HTML content
    echo $htmlContent;
    ?>
</body>
</html>
